# Generated by Django 5.0 on 2023-12-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
