# Generated by Django 5.0 on 2023-12-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_alter_photos_options_alter_tours_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='days',
            field=models.IntegerField(default=0, verbose_name='На сколько дней расчитан тур'),
        ),
    ]
