# Generated by Django 5.0 on 2023-12-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_tours_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='everyday',
            field=models.CharField(default='Сумма не выбрана', max_length=100, verbose_name='Дневная оплата'),
        ),
    ]
